# Generated by Django 4.2.3 on 2023-09-06 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='aeropuerto',
            name='triper',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='trip',
            name='triper',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
